server {
    listen 80;
    server_name localhost;

    location /NexusFrontEnd {
        alias /usr/share/nginx/html/NexusFrontEnd;
        try_files $uri $uri/ /NexusFrontEnd/index.html;
    }

    location / {
        rewrite ^/$ /NexusFrontEnd/ redirect;
    }
}
